apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
  namespace: nginx-ns
spec:
  schedule: "* * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        metadata:
         name: cronjob-pod
        spec:
          containers:
            - name: cronjob-container
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - echo "Hello from CronJob!" && date
          restartPolicy: OnFailure  # Restart if it fails

